### ISSUE TITLE
Type checker fails with mocks

### ISSUE THREAD

**Issue by fornellas** [facebookincubator/TestSlide#130]
[This PR](https://github.com/facebookincubator/TestSlide/pull/124) added type checking for function calls. It works as expected, but it is failing when a call is made using a mock, but it should not.

Suggestion on how to fix this:

- Have a constant with a list of known mock classes: Python's unittest (eg: the ones [listed here](https://testslide.readthedocs.io/en/2.3.0/strict_mock/index.html#yet-another-mock)) and StrictMock.
- Have a map of mock class to a function that extracts its template:
  - For `StrictMock`, get the given `template` (IIRC mock_callable already does this, there's a trick there).
  - For Python's unittest, get the [`spec`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock).

Using that:

- If the given argument is a mock:
  - Without a template / spec, then do no type checking.
  - With a template, do type checking using the template.

**Comment by david-caro** [comment]
I sent a PR, not 100% sure if that's what you meant that was the problem xd

**Comment by fornellas** [comment]
PR is legit! This was exactly the problem, thanks!
