### ISSUE TITLE
Get rid of `signature_validation` parameter

### ISSUE THREAD

**Issue by fornellas** [facebookincubator/TestSlide#173]
With the introduction of the `type_validation` parameter, `signature_validation` became redundant: it can only be disabled if `type_validation` is also disabled.

Let's get rid of `signature_validation`:

```
docs/strict_mock/index.rst
testslide/strict_mock.py
tests/strict_mock_testslide.py
```

**Comment by deathowl** [comment]
@fornellas  now which one should we get rid of ? :P Task title says signature_validation. Task body says type_validation :octocat:

**Comment by fornellas** [comment]
`signature_validation`, just fixed it, tkz!
