### ISSUE TITLE
Create issue and pull request templates

### ISSUE THREAD

**Issue by fornellas** [facebookincubator/TestSlide#187]
As per [GH documentation](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).

For bug reports, I suggest something like:

I'm using TestSlide `$VERSION`.

Given `repro_test.py` containing:

```python
import testslide

class Repro(testslide.TestCase):
  def test_repro(self):
    pass
```

When I run:

```
$ testslide repro_test.py
```

I expected `this to happen`, but instead, `that happened`.

**Comment by cereblanco** [comment]
I can work on this. :)
