### ISSUE TITLE
Make _Config in runner.py class a dataclass so we can remove the whole lot of type: ignore-s from later parts of cli.py 

### ISSUE THREAD

**Issue by deathowl** [facebookincubator/TestSlide#247]
This not being a dataclass causes a lots of confusion for mypy, and rightfully so. This is not the nicest. Make it a dataclass or replace everything with click :)

**Comment by xiaoxianma** [comment]
@deathowl Hi, I'd like to work on this. To double-check, do you mean _Config class in cli.py? We can make it dataclass to that we can refactor _get_config_from_parsed_args. And what does it mean "ignore-s from later parts of cli.py"?

**Comment by deathowl** [comment]
Hey! Thanks for reaching out . Yeah, it makes https://github.com/facebookincubator/TestSlide/blob/master/testslide/cli.py#L332 really not nice to have so many type: ignore-s. The easier way could be to turn _Config into a dataclass that holds configuration.
The harder but nicer way would be to move cli.py to use `click` so we wouldn't need to worry about this at all. Ping the thread if you need any help :)

**Comment by xiaoxianma** [comment]
Yeah, maybe I can think about moving to `click` directly. Do we have test for cli.py so that my refactor won't break?

**Comment by fornellas** [comment]
Click <3

There should be thorough test coverage for the CLI: `make tests/cli_unittest.py V=1`. Those work by spawning the binary and asserting on output, so, click / no click, they should work the same for the most part.
