### ISSUE TITLE
How to do conditional Skip?

### ISSUE THREAD

**Issue by xush6528** [facebookincubator/TestSlide#43]
How to skip a TestSlide example, if I known in certain environment the test is expceted to fail or does not make sense.
Like the Python unittest module API. 
https://fburl.com/ljc095sq

**Comment by fornellas** [comment]
https://testslide.readthedocs.io/en/1.5.0/testslide_dsl/skip_and_focus/index.html#skip

xexample is the way to go for unconditional skip. However it is just regular Python, this also works:

```python
if should_have_example:
  @context.example
  def whatever(self):
```

Real world example https://github.com/facebookincubator/TestSlide/blob/master/tests/mock_callable_testslide.py#L179. 

I suppose we could have some syntax sugar for that like:

```python
@context.example(skip=should_skip)
```

But it seems no to be strictly needed.

What do you think?

**Comment by xsh6528** [comment]
The daily use case for my work is that we have some test examples that only runs on GPU CUDA devices.

But CI could pick building and testing our project in either environment, ones with CPU+GPU or ones that has CPU only.

We used `@unittest.skipUnless(cuda.is_available())` a lot.

In TestSlide, we will have to write this to circumvent

```Python
If not cuda.is_available():
    return
```

And, more importantly, the test runner **will not remind me that the test is skipped**.

**Comment by xsh6528** [comment]
@fornellas  Thanks, I will try this way. Conditionally declare contexts and examples.

**Comment by fornellas** [comment]
Cool. I'm closing this then, as it seems you have a way for conditionally skip. Feel free to reopen if you feel like it deserves some syntax sugar.

**Comment by xsh6528** [comment]
After trying it out, I feel it's still needed.

Because it would be great to have a "SKIP" item in test runner results, just like @context.xexample does.

**Comment by fornellas** [comment]
NP. So, how do you think the syntax should go?

```python
@context.example(skip=should_skip)
```

Is it ok like this?

**Comment by xsh6528** [comment]
Thanks for opening it.

It looks great.

One thing worthy noticins is that, after searching in my company's repo, I noticed that `@unittest.skipUnless(condition)` has 2x usage than `@unittest.skip(condition)`.

That means with this simple syntax, we need to expect a lot of
```
@context.example(skip=not should_run_example)
```
